export type ConsumivelCatalogItem = {
	nome: string;
	tamanho_sache_g?: number;
	carboidratos_g: number;
	sodio_mg: number;
	taurina_mg?: number | null;
	cafeina_mg?: number | null;
	nitrato_mg?: number | null;
};

export type ConsumiveisPorMarca = {
	marca: string;
	produtos: ConsumivelCatalogItem[];
};

export const consumiveisPorMarca: ConsumiveisPorMarca[] = [
	{
		marca: "Z2",
		produtos: [
			{
				nome: "Energy Gel Z2 Pitaya",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 300,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Energy Gel Z2 Tropical Fruit",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Energy Gel Z2 Tangerine",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 200,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Energy Gel Z2 Pink Lemonade",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 200,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Energy Gel Z2 Choco Truffle",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 200,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Energy Gel Z2 Maratona do Rio Água de Coco",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 344,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Energy Gel Z2+ Double Expresso",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 100,
				taurina_mg: 500,
				cafeina_mg: 200,
			},
			{
				nome: "Energy Gel Z2+ Iced Coffee",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 200,
				taurina_mg: 500,
				cafeina_mg: 150,
			},
			{
				nome: "Energy Gel Z2+ Freezin' Cola",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 300,
				taurina_mg: 500,
				cafeina_mg: 200,
			},
			{
				nome: "Energy Gel Z2+ Lime",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 200,
				taurina_mg: 500,
				cafeina_mg: 100,
			},
			{
				nome: "Energy Gel Z2+ Choco Mint",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 100,
				taurina_mg: 500,
				cafeina_mg: 150,
			},
			{
				nome: "Energy Gel Z2+ Maratona do Rio Mate & Limão",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 229,
				taurina_mg: 500,
				cafeina_mg: 100,
			},
			{
				nome: "Energy Gel Z2 Original",
				tamanho_sache_g: 55,
				carboidratos_g: 40,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Energy Gel Z2+ Original",
				tamanho_sache_g: 55,
				carboidratos_g: 40,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: 100,
			},
			{
				nome: "Energy Gel Z2+ 25 LoadUp MPR",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: 100,
			},
		],
	},

	{
		marca: "pace it",
		produtos: [
			{
				nome: "Hidrogel Pace It Morango com Limão",
				tamanho_sache_g: 45,
				carboidratos_g: 30,
				sodio_mg: 300,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Hidrogel Pace It Neutro",
				tamanho_sache_g: 45,
				carboidratos_g: 30,
				sodio_mg: 200,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Hidrogel Pace It Sweet Banana",
				tamanho_sache_g: 45,
				carboidratos_g: 30,
				sodio_mg: 342,
				taurina_mg: null,
				cafeina_mg: 75,
			},
			{
				nome: "Hidrogel Pace It Tropical",
				tamanho_sache_g: 45,
				carboidratos_g: 30,
				sodio_mg: 242,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Hidrogel Pace It Freeze",
				tamanho_sache_g: 45,
				carboidratos_g: 30,
				sodio_mg: 182,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Hidrogel Pace It Limão",
				tamanho_sache_g: 45,
				carboidratos_g: 30,
				sodio_mg: 80,
				taurina_mg: null,
				cafeina_mg: null,
			},
			{
				nome: "Hidrogel Pace It Cappuccino",
				tamanho_sache_g: 45,
				carboidratos_g: 30,
				sodio_mg: 300,
				taurina_mg: null,
				cafeina_mg: 150,
			},
		],
	},
	{
		marca: "dobro",
		produtos: [
			{
				nome: "Carbs Gel Neutro Fresh",
				tamanho_sache_g: 30,
				carboidratos_g: 21,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: null,
			},
			{
				nome: "Carbs Gel Jabuticaba",
				tamanho_sache_g: 30,
				carboidratos_g: 21,
				sodio_mg: 200,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: null,
			},
			{
				nome: "Carbs Gel 40g Neutro Fresh",
				tamanho_sache_g: 55,
				carboidratos_g: 40,
				sodio_mg: 180,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: null,
			},
			{
				nome: "Carbs Gel 40g Neutro Fresh com Cafeína",
				tamanho_sache_g: 55,
				carboidratos_g: 40,
				sodio_mg: 180,
				taurina_mg: null,
				cafeina_mg: 180,
				nitrato_mg: null,
			},
			{
				nome: "Carbs Gel Neutro Fresh com Cafeína",
				tamanho_sache_g: 30,
				carboidratos_g: 21,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: 100,
				nitrato_mg: null,
			},
			{
				nome: "Carbs Gel Tropical com Cafeína",
				tamanho_sache_g: 30,
				carboidratos_g: 21,
				sodio_mg: 200,
				taurina_mg: null,
				cafeina_mg: 150,
				nitrato_mg: null,
			},
			{
				nome: "Carbs Gel Maracujá",
				tamanho_sache_g: 30,
				carboidratos_g: 21,
				sodio_mg: 200,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: null,
			},
			{
				nome: "HIDROGEL Neutro",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 108,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: null,
			},
			{
				nome: "HIDROGEL Neutro com Cafeína",
				tamanho_sache_g: 40,
				carboidratos_g: 25,
				sodio_mg: 107,
				taurina_mg: null,
				cafeina_mg: 100,
				nitrato_mg: null,
			},
			{
				nome: "BT Gel Beterraba com Acerola",
				tamanho_sache_g: 30,
				carboidratos_g: 20,
				sodio_mg: 150,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: null,
			},
			{
				nome: "BT Gel Beterraba com Laranja",
				tamanho_sache_g: 30,
				carboidratos_g: 20,
				sodio_mg: 46,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: null,
			},
			{
				nome: "BT Gel Beterraba com Limão e Cafeína",
				tamanho_sache_g: 30,
				carboidratos_g: 20,
				sodio_mg: 46,
				taurina_mg: null,
				cafeina_mg: 35,
				nitrato_mg: null,
			},
			{
				nome: "BT Gel Beterraba com Guaraná com Cafeína",
				tamanho_sache_g: 30,
				carboidratos_g: 20,
				sodio_mg: 150,
				taurina_mg: null,
				cafeina_mg: 75,
				nitrato_mg: null,
			},
			{
				nome: "BT 400 Nitrato Gel Laranja e Morango",
				tamanho_sache_g: 30,
				carboidratos_g: 21,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: 400,
			},
			{
				nome: "BT 400 Nitrato Gel Blueberry",
				tamanho_sache_g: 30,
				carboidratos_g: 22,
				sodio_mg: 200,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: 400,
			},
			{
				nome: "BT 400 Nitrato Gel Pink Lemonade com Cafeína e Citrulina",
				tamanho_sache_g: 30,
				carboidratos_g: 22,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: 100,
				nitrato_mg: 400,
			},
			{
				nome: "BT 400 Nitrato Gel Redberry com Cafeína",
				tamanho_sache_g: 30,
				carboidratos_g: 20,
				sodio_mg: 200,
				taurina_mg: 500,
				cafeina_mg: 100,
				nitrato_mg: 400,
			},
			{
				nome: "BT 400 Nitrato Gel Limão e Gengibre com Cafeína",
				tamanho_sache_g: 30,
				carboidratos_g: 21,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: 400,
			},
			{
				nome: "BT 400 Nitrato Gel Açaí Frooty",
				tamanho_sache_g: 30,
				carboidratos_g: 21,
				sodio_mg: 100,
				taurina_mg: null,
				cafeina_mg: null,
				nitrato_mg: 400,
			},
		],
	},
];
